// prisma/exemplos/ingrediente.js
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
    await prisma.ingrediente.createMany({
      data: [
        { id_tipo_ingrediente: 1, descricao_ingrediente: 'Carne bovina moída', valor: 25.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 1, descricao_ingrediente: 'Carne bovina bife', valor: 39.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 1, descricao_ingrediente: 'Carne bovina costela', valor: 45.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 1, descricao_ingrediente: 'Carne bovina picanha', valor: 60.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 1, descricao_ingrediente: 'Carne bovina alcatra', valor: 55.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 1, descricao_ingrediente: 'Carne bovina filé mignon', valor: 80.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Coxa e sobrecoxa de frango', valor: 20.50, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Peito de frango desossado', valor: 25.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Peito de frango com osso', valor: 22.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Asa de frango', valor: 18.50, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Sobrecoxa de frango', valor: 20.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Peito de frango com pele', valor: 26.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 2, descricao_ingrediente: 'Coxa de frango', valor: 18.50, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 3, descricao_ingrediente: 'Filé de tilápia', valor: 22.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 3, descricao_ingrediente: 'Filé de merluza', valor: 25.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 3, descricao_ingrediente: 'Filé de salmão', valor: 50.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 3, descricao_ingrediente: 'Filé de sardinha', valor: 15.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 3, descricao_ingrediente: 'Camarão', valor: 55.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Leite integral', valor: 4.80, id_uni_medida: 4, quantidade: 1   },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Leite desnatado', valor: 4.50, id_uni_medida: 4, quantidade: 1  },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Leite em pó', valor: 20.00, id_uni_medida: 2, quantidade: 400 },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Queijo mussarela', valor: 53.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Queijo parmesão', valor: 60.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Queijo prato', valor: 55.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Queijo minas', valor: 50.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Creme de leite', valor: 4.50, id_uni_medida: 2, quantidade: 200 },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Leite condensado', valor: 5.50, id_uni_medida: 2, quantidade: 395 },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Iogurte natural', valor: 3.50, id_uni_medida: 2, quantidade: 170 },
        { id_tipo_ingrediente: 4, descricao_ingrediente: 'Iogurte grego', valor: 5.50, id_uni_medida: 2, quantidade: 170 },
        { id_tipo_ingrediente: 5, descricao_ingrediente: 'Batata', valor: 3.20, id_uni_medida: 1, quantidade: 1  },        
        { id_tipo_ingrediente: 5, descricao_ingrediente: 'Batata-doce', valor: 3.50, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 5, descricao_ingrediente: 'Cenoura', valor: 2.50, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 5, descricao_ingrediente: 'Brócolis', valor: 5.00, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 6, descricao_ingrediente: 'Alface', valor: 2.50, id_uni_medida: 11, quantidade: 1  },
        { id_tipo_ingrediente: 6, descricao_ingrediente: 'Almeirão', valor: 5.50, id_uni_medida: 11, quantidade: 1  },
        { id_tipo_ingrediente: 7, descricao_ingrediente: 'Maçã', valor: 5.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 7, descricao_ingrediente: 'Banana', valor: 6.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 7, descricao_ingrediente: 'Laranja', valor: 4.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 7, descricao_ingrediente: 'Abacaxi', valor: 8.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 7, descricao_ingrediente: 'Manga', valor: 7.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 7, descricao_ingrediente: 'Uva', valor: 10.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Arroz', valor: 28.00, id_uni_medida: 1, quantidade: 5  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Arroz integral', valor: 30.00, id_uni_medida: 1, quantidade: 5  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Arroz parboilizado', valor: 32.00, id_uni_medida: 1, quantidade: 5  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Feijão preto', valor: 9.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Feijão carioca', valor: 6.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Feijão branco', valor: 7.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 8, descricao_ingrediente: 'Lentilha', valor: 10.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Sal', valor: 3.99, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Pimenta-do-reino em grão', valor: 4.50, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Pimenta-do-reino moída', valor: 4.50, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Pimenta calabresa', valor: 4.50, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Páprica doce', valor: 4.00, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Colorau', valor: 2.50, id_uni_medida: 2, quantidade: 100 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Cominho', valor: 3.00, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Tempero baiano', valor: 2.80, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Alho em pó', valor: 4.50, id_uni_medida: 2, quantidade: 100 },
        { id_tipo_ingrediente: 9, descricao_ingrediente: 'Cebola em pó', valor: 4.50, id_uni_medida: 2, quantidade: 100 },
        { id_tipo_ingrediente: 10, descricao_ingrediente: 'Farinha de trigo', valor: 4.50, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 10, descricao_ingrediente: 'Farinha de arroz', valor: 12.50, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 10, descricao_ingrediente: 'Farinha de aveia', valor: 9.50, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Óleo de soja', valor: 6.00, id_uni_medida: 4, quantidade: 1 },
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Óleo de girassol', valor: 12.00, id_uni_medida: 4, quantidade: 1 },
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Óleo de canola', valor: 10.00, id_uni_medida: 4, quantidade: 1 },
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Óleo de milho', valor: 8.00, id_uni_medida: 4, quantidade: 1 },
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Manteiga', valor: 15.00, id_uni_medida: 2, quantidade: 250},
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Margarina', valor: 7.00,id_uni_medida: 2, quantidade: 500 },
        { id_tipo_ingrediente: 11, descricao_ingrediente: 'Azeite de oliva', valor: 30.00, id_uni_medida: 4, quantidade: 1 },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Açúcar refinado', valor: 7.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Açúcar cristal', valor: 8.00, id_uni_medida: 1, quantidade: 2 },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Açúcar demerara', valor: 12.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Açúcar mascavo', valor: 15.00, id_uni_medida: 1, quantidade: 1  },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Chocolate em pó', valor: 11.00, id_uni_medida: 2, quantidade: 400  },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Cacau em pó', valor: 16.00, id_uni_medida: 2, quantidade: 250  },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Mel', valor: 20.00, id_uni_medida: 5, quantidade: 500 },
        { id_tipo_ingrediente: 12, descricao_ingrediente: 'Adoçante', valor: 10.00, id_uni_medida: 5, quantidade: 100 },
        { id_tipo_ingrediente: 13, descricao_ingrediente: 'Suco de laranja', valor: 15.50, id_uni_medida: 4, quantidade: 1 },  
        { id_tipo_ingrediente: 13, descricao_ingrediente: 'Suco de uva', valor: 15.50, id_uni_medida: 4, quantidade: 1 },        
        { id_tipo_ingrediente: 13, descricao_ingrediente: 'Água', valor: 2.50, id_uni_medida: 4, quantidade: 1},
        { id_tipo_ingrediente: 13, descricao_ingrediente: 'Pinga', valor: 5.00, id_uni_medida: 4, quantidade: 1 },  
        { id_tipo_ingrediente: 13, descricao_ingrediente: 'Vinho', valor: 20.00, id_uni_medida: 4, quantidade: 1 },    
        { id_tipo_ingrediente: 14, descricao_ingrediente: 'Fermento químico', valor: 2.20, id_uni_medida: 2, quantidade: 10 },
        { id_tipo_ingrediente: 14, descricao_ingrediente: 'Fermento em pó', valor: 5.20, id_uni_medida: 2, quantidade: 50 },
        { id_tipo_ingrediente: 15, descricao_ingrediente: 'Salsinha', valor: 1.50, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 15, descricao_ingrediente: 'Cebolinha', valor: 1.50, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 15, descricao_ingrediente: 'Manjericão fresco', valor: 2.00, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Milho verde enlatado', valor: 3.50, id_uni_medida: 2, quantidade: 170 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Ervilha enlatada', valor: 3.00, id_uni_medida: 2, quantidade: 170 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Azeitona verde', valor: 5.00, id_uni_medida: 2, quantidade: 200 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Azeitona preta', valor: 5.00, id_uni_medida: 2, quantidade: 200 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Palmito', valor: 10.00, id_uni_medida: 2, quantidade: 300 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Cogumelo', valor: 15.00, id_uni_medida: 2, quantidade: 200 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Pepino em conserva', valor: 4.00, id_uni_medida: 2, quantidade: 300 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Picles', valor: 4.50, id_uni_medida: 2, quantidade: 300 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Pimentão', valor: 3.00, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Cebola', valor: 2.00, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Alho', valor: 2.50, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 16, descricao_ingrediente: 'Gengibre', valor: 3.00, id_uni_medida: 11, quantidade: 1 },
        { id_tipo_ingrediente: 17, descricao_ingrediente: 'Ovo de galinha', valor: 25.00, id_uni_medida: 11, quantidade: 30 },
        { id_tipo_ingrediente: 17, descricao_ingrediente: 'Ovo de codorna', valor: 30.00, id_uni_medida: 11, quantidade: 12 },
        { id_tipo_ingrediente: 17, descricao_ingrediente: 'Ovo de pata', valor: 35.00, id_uni_medida: 11, quantidade: 12 },
        { id_tipo_ingrediente: 17, descricao_ingrediente: 'Requeijão cremoso', valor: 8.50, id_uni_medida: 2, quantidade: 250 },
        { id_tipo_ingrediente: 18, descricao_ingrediente: 'Macarrão espaguete', valor: 4.00, id_uni_medida: 2, quantidade: 500 },
        { id_tipo_ingrediente: 18, descricao_ingrediente: 'Macarrão parafuso', valor: 4.20, id_uni_medida: 2, quantidade: 500 },
        { id_tipo_ingrediente: 18, descricao_ingrediente: 'Massa de lasanha', valor: 6.90, id_uni_medida: 2, quantidade: 500 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Presunto', valor: 6.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Calabresa', valor: 10.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Bacon', valor: 12.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Peito de peru', valor: 8.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Linguiça calabresa', valor: 10.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Linguiça toscana', valor: 12.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Linguiça de frango', valor: 8.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Linguiça de pernil', valor: 10.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Linguiça de porco', valor: 12.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Linguiça', valor: 8.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 19, descricao_ingrediente: 'Salsicha', valor: 12.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão francês', valor: 0.50, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de forma', valor: 5.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de hambúrguer', valor: 6.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de hot dog', valor: 6.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de queijo', valor: 8.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão sírio', valor: 4.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de batata', valor: 5.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de alho', valor: 7.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de cebola', valor: 7.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de milho', valor: 7.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de forma integral', valor: 6.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 20, descricao_ingrediente: 'Pão de forma sem glúten', valor: 10.00, id_uni_medida: 1, quantidade: 1 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Molho de tomate', valor: 4.00, id_uni_medida: 2, quantidade: 340 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Molho shoyu', valor: 7.00, id_uni_medida: 2, quantidade: 150 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Molho inglês', valor: 9.00, id_uni_medida: 2, quantidade: 150 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Molho barbecue', valor: 12.00, id_uni_medida: 2, quantidade: 300 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Molho pesto', valor: 20.00, id_uni_medida: 2, quantidade: 200 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Maionese', valor: 6.00, id_uni_medida: 2, quantidade: 500 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Ketchup', valor: 5.00, id_uni_medida: 2, quantidade: 400 },
        { id_tipo_ingrediente: 21, descricao_ingrediente: 'Mostarda', valor: 4.50, id_uni_medida: 2, quantidade: 400 },

      ],
    });
  
    console.log('Ingredientes criados!');
  }


main()
.catch(e => {
  console.error(e);
  process.exit(1);
})
.finally(() => prisma.$disconnect());
